name:                musicology-extra
version:             0.1.0.0
github:              "DCMLab/haskell-musicology"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "2019 Christoph Finkensiep"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/DCMLab/haskell-musicology#readme>

dependencies:
- base >= 4.7 && < 5
- musicology-core
- safe
- containers
- unordered-containers
- deepseq
- Frames
- mtl
- machines
- vinyl
- mwc-random
- primitive
- HCodecs
- vector
- microlens
- template-haskell
- filepath
- directory

library:
  source-dirs: src

tests:
  musicology-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicology-core
    - hspec
    - QuickCheck
