name:                musicology-musicxml
version:             0.1.0.0
github:              "chfin/musicology-musicxml"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "Christoph Finkensiep"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chfin/musicology-musicxml#readme>

dependencies:
- base >= 4.7 && < 5
- musicology-core
- xml
- Frames
- bytestring
- mtl
- vector
- vinyl
- pipes
- text
- aeson
- containers
- microlens

library:
  source-dirs: src

executables:
  musicology-musicxml-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicology-musicxml
  musicxml2json:
    main:                Main.hs
    source-dirs:         app/tojson
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicology-musicxml
    - optparse-applicative
    - aeson-pretty

tests:
  musicology-musicxml-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicology-musicxml
