name:                musicology-core
version:             0.1.0.0
github:              "DCMLab/haskell-musicology"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "2021 Christoph Finkensiep"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chfin/musicology-core#readme>

dependencies:
- base >= 4.7 && < 5
- musicology-pitch
- aeson
- microlens
- deepseq
- hashable

library:
  source-dirs: src

tests:
  musicology-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - musicology-core
